version: '3.8'
services:
  svm_backend:
    container_name: svm_backend_container
    build: ./backend
    ports:
      - "5000:5000"
    restart: always

  vgg19_backend:
    container_name: vgg19_backend_container
    build: ./backend_vgg19
    ports:
      - "5001:5000"
    restart: always

  frontend:
    container_name: frontend_container
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - svm_backend
      - vgg19_backend

